meta:
    site_title: "雁起平沙的文艺博客"
    site_subtitle: "人生就是不停的战斗"
    site_language: "zh-cn"
    absolute_baseurl: http://art.yanping.me
    domain: yanping.me
    author:
        full_name:Chen Yanping
        short_name: ypchen
        name: ypchen
        email: chen@yanping.me

tag_dir: tag
# baseurl: /
markdown: rdiscount
pygments: false
permalink: /:year/:month/:day/:title

debug: false

